from django.db import models


class Products(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=50)
    supplier = models.CharField(max_length=50, blank=True, null=True)
    code = models.CharField(unique=True, max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255)
    tax_included = models.DecimalField(max_digits=10, decimal_places=2)
    buyingprice = models.CharField(max_length=50)
    sellingprice = models.CharField(max_length=50)
    promoprice = models.CharField(max_length=50, blank=True, null=True)
    wholesaleprice = models.CharField(max_length=50)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    reorderevel = models.IntegerField(blank=True, null=True)
    allow_alt_description = models.IntegerField()
    is_serialized = models.IntegerField()
    imgid = models.CharField(max_length=255, blank=True, null=True)
    override_default_tax = models.IntegerField()
    is_service = models.IntegerField()
    deleted = models.IntegerField()
    qty = models.DecimalField(max_digits=10, decimal_places=2)
    dateposted = models.CharField(max_length=50)
    userid = models.CharField(max_length=50)
    companyid = models.CharField(max_length=100)
    store = models.CharField(max_length=50)
    expdate = models.DateField()
    orderamount = models.CharField(max_length=50)
    taxtype = models.CharField(max_length=30)
    shortname = models.CharField(max_length=50)
    status = models.CharField(max_length=30)
    uom = models.CharField(max_length=20)
    producttype = models.CharField(max_length=30)
    assetaccount = models.CharField(max_length=30)
    salesaccount = models.CharField(max_length=30)
    expenseaccount = models.CharField(max_length=30)
    vattype = models.CharField(max_length=20)
    reorderquantity = models.CharField(max_length=20, blank=True, null=True)
    hscode = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'products'
        
class SalesOrder(models.Model):
    myinvoice = models.CharField(unique=True, max_length=50, blank=True, null=True)
    invoice = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    qty = models.CharField(max_length=10)
    amount = models.CharField(max_length=100)
    salestype = models.CharField(max_length=100)
    discount = models.CharField(max_length=100)
    dateposted = models.CharField(max_length=50)
    address = models.TextField()
    description = models.TextField()
    user = models.CharField(max_length=50)
    bprice = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    tax = models.DecimalField(max_digits=10, decimal_places=2)
    sprice = models.CharField(max_length=100)
    balance = models.CharField(max_length=50)
    customer = models.CharField(max_length=50)
    userid = models.CharField(max_length=50)
    mode = models.CharField(max_length=50)
    companyid = models.CharField(max_length=100)
    date = models.DateTimeField()
    maincategory = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    status = models.CharField(max_length=30, blank=True, null=True)
    branch = models.CharField(max_length=30)
    ordersales = models.CharField(max_length=20)
    uom = models.CharField(max_length=30)
    sales = models.CharField(max_length=30)
    updatedat = models.CharField(max_length=50)
    updatedby = models.CharField(max_length=10)
    taxindicator = models.CharField(max_length=10)
    serial = models.CharField(max_length=50, blank=True, null=True)
    tax2 = models.CharField(max_length=20)
    discountype = models.CharField(max_length=20)
    discountvalue = models.CharField(max_length=20)
    vattype = models.CharField(max_length=20)
    taxable = models.DecimalField(max_digits=10, decimal_places=2)
    uomqty = models.CharField(max_length=30)
    stockbefore = models.CharField(max_length=30)
    stockafter = models.CharField(max_length=30)
    taxtype = models.CharField(max_length=30)
    stock = models.CharField(max_length=20)
    producttype = models.CharField(max_length=30)
    assetaccount = models.CharField(max_length=30)
    salesaccount = models.CharField(max_length=30)
    expenseaccount = models.CharField(max_length=30, blank=True, null=True)
    start = models.CharField(max_length=20)
    close = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'sales_order'

class Attendance(models.Model):
    idno = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date = models.DateTimeField()
    timein = models.CharField(max_length=100)
    timeout = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    createddate = models.CharField(max_length=100)
    comment = models.TextField()
    timediffrence = models.CharField(max_length=5)
    device = models.CharField(max_length=30)
    totaltime = models.CharField(max_length=20, blank=True, null=True)
    checkoutime = models.DateTimeField()
    status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'attendance'


class Customer(models.Model):
    firstname = models.CharField(max_length=100)
    surname = models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    business = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    createddate = models.CharField(max_length=50)
    password = models.CharField(max_length=30)
    website = models.CharField(max_length=100)
    dob = models.CharField(max_length=50)
    idno = models.CharField(max_length=50)
    description = models.TextField()
    box = models.CharField(max_length=50)
    source = models.CharField(max_length=50, blank=True, null=True)
    town = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    updatedate = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    apiaccount_id = models.CharField(max_length=30)
    recoverpassword = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    companyid = models.IntegerField()
    service = models.TextField()
    usertype = models.CharField(max_length=50, blank=True, null=True)
    smstype = models.IntegerField()
    refer = models.TextField()
    email = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'customer'

class Tables(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    createdate = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    userid = models.CharField(max_length=50)
    updatedate = models.CharField(max_length=50)
    companyid = models.CharField(max_length=50)
    branchid = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'tables'


class Invoice(models.Model):
    plotno = models.CharField(max_length=60)
    houseno = models.CharField(max_length=40)
    tenantid = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    month = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    createdat = models.CharField(max_length=100)
    updatedat = models.CharField(max_length=100)
    userid = models.CharField(max_length=100)
    duedate = models.CharField(max_length=40)
    paymentstatus = models.CharField(max_length=40)
    paymentmode = models.CharField(max_length=40)
    paymentcode = models.CharField(max_length=100)
    transactioncode = models.CharField(max_length=100)
    approval = models.CharField(max_length=30)
    approvedby = models.CharField(max_length=60)
    approvaldate = models.CharField(max_length=60)
    totalamount = models.CharField(max_length=40)
    paid = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.CharField(max_length=40)
    companyid = models.CharField(max_length=100)
    commission = models.DecimalField(max_digits=10, decimal_places=2)
    vat = models.DecimalField(max_digits=10, decimal_places=2)
    paymentdate = models.CharField(max_length=30)
    order = models.IntegerField()
    priority = models.IntegerField()
    coparent = models.DecimalField(max_digits=10, decimal_places=2)
    coparentcommission = models.DecimalField(max_digits=10, decimal_places=2)
    coparentvat = models.DecimalField(max_digits=10, decimal_places=2)
    coparentdate = models.CharField(max_length=30)
    coparentuserid = models.IntegerField()
    chargeid = models.CharField(max_length=30)
    branchid = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'invoice'
