# Generated by Django 4.2.4 on 2023-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'mainmenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('tax_included', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyingprice', models.CharField(max_length=50)),
                ('sellingprice', models.CharField(max_length=50)),
                ('promoprice', models.CharField(blank=True, max_length=50, null=True)),
                ('wholesaleprice', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reorderevel', models.IntegerField(blank=True, null=True)),
                ('allow_alt_description', models.IntegerField()),
                ('is_serialized', models.IntegerField()),
                ('imgid', models.CharField(blank=True, max_length=255, null=True)),
                ('override_default_tax', models.IntegerField()),
                ('is_service', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateposted', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('companyid', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=50)),
                ('expdate', models.DateField()),
                ('orderamount', models.CharField(max_length=50)),
                ('taxtype', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('uom', models.CharField(max_length=20)),
                ('producttype', models.CharField(max_length=30)),
                ('assetaccount', models.CharField(max_length=30)),
                ('salesaccount', models.CharField(max_length=30)),
                ('expenseaccount', models.CharField(max_length=30)),
                ('vattype', models.CharField(max_length=20)),
                ('reorderquantity', models.CharField(blank=True, max_length=20, null=True)),
                ('hscode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
